import requests
import logging
import openpyxl
import json
import math
import logging
import datetime
from check_user_status import rest_get_user_validations_jql_call

# Logger configurations
file_name = "Check_Current_Allocation_Log_" + str (datetime.date.strftime(datetime.datetime.now(), "%Y-%m-%d__%H-%M-%S"))
logger_file_path = "D:\\Script_Outputs\\" + str(file_name) + ".txt"
logging.basicConfig(filename=logger_file_path,
                    format='%(asctime)s : %(levelname)s : %(message)s',
                    filemode='a', level=logging.INFO)
logger = logging.getLogger()

###################################################################

def rest_get_Current_Allocation_Full_v_1_0(inp_email_id,inp_start_date,inp_end_date, inp_max_hours):

    # -->> This is because the user cannot have a single record in system with a allocation of > req_alloc
    #inp_req_hours = 8 - float(inp_req_hours)  #-Bcoz 6.4 usecase failed with 1.5999999999999996
    '''
    inp_req_hours = 8 - inp_req_hours
    inp_req_hours = round(inp_req_hours,2)
    '''
    sums_by_date = {}
    sorted_sums ={}
    rest_status_code, rest_payload  = rest_get_Allocation_check_API_Call_Loop(inp_email_id,inp_start_date,inp_end_date,0)

    if rest_status_code == 200:
        record_count = rest_payload['total']
        if record_count > 0:
                loop_count = math.ceil( record_count / 100 ) + 1    ## To execute the for loop accordingly ie ( For 1 to 1) stops at 1 itself
                record_no = 0
                logger.info(inp_email_id + " - loop count is " + str(loop_count) + " for total records - " + str(record_count))
                for i in range(1, loop_count):
                    logger.info(inp_email_id + " : -> -> ->  processing loop " + str(i) + " of " + str(record_count) + " records" + " ---> starting with " + str(record_no))
                    rest_status_code, rest_payload  = rest_get_Allocation_check_API_Call_Loop(inp_email_id,inp_start_date,inp_end_date,record_no)
                    
                    for issue in rest_payload['issues']:
                        date = issue['fields']['customfield_11030']
                        allo_hours = issue['fields']['customfield_11024']
                        #sums_by_date[date] = sums_by_date.get(date, 0) + allo_hours  ## If you want to retrieve the value for a key that doesn't exist in the dictionary, you can provide a default value [0] to be returned instead
                        sums_by_date[date] = round(sums_by_date.get(date, 0) + allo_hours, 2)
                                                
                    
                    #Individual Loop overallocation check - to bypass rest of the execution through return statement
                    '''
                    over_allocated_single_loop = {k:v for k, v in sums_by_date.items() if v > inp_req_hours}
                    if len(over_allocated_single_loop) > 0:
                        returned_total_alloc_status = "One or more excess allocation('s) already been locked for the resource, Hence Rejected --->>> " + str(dict(sorted(over_allocated_single_loop.items())))
                        logger.warning (inp_email_id + " - exiting loop in --> loop " + str(i) + " - " + returned_total_alloc_status)
                        return returned_total_alloc_status
                    '''
                    #Increase record count by 100 for next page in loop
                    record_no = record_no + 100
                
               #Loop complete  : Execute Final Check with all reocords generated by complete loops ->
                over_allocated_final_check = {k:v for k, v in sums_by_date.items() if v > inp_max_hours}
                if len(over_allocated_final_check) > 0:
                    returned_total_alloc_status = "Warning !! Over allocations found --->>> " + str(dict(sorted(over_allocated_final_check.items())))
                else:
                    returned_total_alloc_status = "Allocations are within the limit"

                logger.info (inp_email_id + " ==> " + returned_total_alloc_status)

                # Finally - print existing total allocation for given user    
                sorted_sums = dict(sorted(sums_by_date.items())) 
                logger.info(inp_email_id + " - Total allocation list as of now - " + str(len(sorted_sums)) + str(sorted_sums))
            
            
        else:
             logger.info(inp_email_id + " -  " + "No existing allocations found for user")
             returned_total_alloc_status = "No Allocations Found"
                  
    else:
        returned_total_alloc_status  = "_RestCallERROR_ --> " + str(rest_status_code)

    return returned_total_alloc_status,sorted_sums

## ---------------------------------------------------------------------------------

def rest_get_Allocation_check_API_Call_Loop(inp_email_id,inp_start_date,inp_end_date, pagination_no):

    created_jql = "project = JRT AND issuetype = 'Daily Allocation' AND status = 'Allocated' AND 'JRT_Resource Email' ~ '" +  str(inp_email_id) + "' and JRT_Date >= '" + str(inp_start_date)[0:10] + "' and  JRT_Date <= '" + str(inp_end_date)[0:10] + "'"
    #created_jql = "project = JRT AND issuetype = 'Daily Allocation' AND status = 'Allocated' AND 'JRT_Resource Email' ~ '" +  str(inp_email_id) + "' and JRT_Date >= '" + str(inp_start_date)[0:10] + "' and  JRT_Date <= '" + str(inp_end_date)[0:10] + "' and 'JRT_Hours per Day[Number]' > " + str(inp_req_hours)
    pagination_startAt = pagination_no
    maxResults = 100

    endpoint = "https://aifel.atlassian.net/rest/api/3/search?"
    token = "Basic bmFkZXNhcGlsbGFpLmdvYmlhbmFudGhAYXhpYXRhZGlnaXRhbGxhYnMuY29tOmpJWXQ0cnhPeFdtMU81VWdQZ2lkODM2MA==" # Nuwanee's Tkn changed to Gobi's

    header_values = {'Content-Type': "application/json",'Accept': "application/json",'Authorization':token}
    input_params = {'jql': created_jql,'fields': "customfield_11024,customfield_11030", 'maxResults' : maxResults, 'startAt': pagination_startAt}

    r = requests.get(url=endpoint, headers=header_values,params=input_params, timeout=10)

    if r.status_code == 200:
        response = r.json()
        #record_count = response['total']
                                       
    else:
        response  = "_RestCallERROR_ --> " + str(r.status_code)
        #record_count = "_RestCallERROR_ --> " + str(r.status_code)

    #return r.status_code, response,record_count
    return r.status_code, response

## ----------To get user allocated work hours from user profile-------------------------------------------------------------------------------
def get_user_profile_max_work_hours(user_email):
    jql = "project = JRT AND issuetype = 'RM Resource Creation' AND status = Active AND 'JRT_Resource Email[Short text]' ~ " + "'" + str(user_email) + "'"
    req_fields= "customfield_10978"
    status_code, response_json = rest_get_user_validations_jql_call (jql,req_fields)

    if status_code == 200:
             if response_json['total'] == 1:
                  max_hours_allocation = response_json['issues'][0]['fields']['customfield_10978']  
             else:
                  max_hours_allocation="Error_Profile"
    else:
        max_hours_allocation="Error_RestCall_" + str(response_json)
         
    return max_hours_allocation
# - ---------------------------------------------------------------------------------------------------------------

###################################################################


if __name__ == "__main__":
   # stuff only to run when not called via 'import' here

    path = "D:\\Roshinie_105953_Backup\\ADL\\VSCodeProjects\\script_inputs\\Bulk_OverAllocation_Check_05092023.xlsx"
    xl_workbook = openpyxl.load_workbook(path)
    xl_sheet = xl_workbook.active

    i_start = 2  # < -- CONFIGURATION
    i_max = 3  # < -- CONFIGURATION
    for i in range(i_start, i_max):
        email_id = xl_sheet.cell(row=i, column=1).value  # < -- Config

        if email_id is not None:

            max_alloc = get_user_profile_max_work_hours(email_id)
            print(str(email_id) + " - Max work allocation hour is --> " + str(max_alloc))
            
            #if (max_alloc[0:5]) != "Error":
            if isinstance(max_alloc,float):
                start_date = xl_sheet.cell(row=i, column=2).value  # < -- Config
                end_date = xl_sheet.cell(row=i, column=3).value  # < -- Config
                #max_alloc = xl_sheet.cell(row=i, column=4).value  # < -- Config  // 30/06/2023 replaced with getting the all_hours from user profile
                record_processed_status = xl_sheet.cell(row=i, column=5).value  # < -- Config

                if [start_date, end_date, max_alloc] is not None:
                    if record_processed_status is None:
                        rest_response, allocation_summary = rest_get_Current_Allocation_Full_v_1_0(email_id, start_date, end_date, max_alloc)
                        xl_sheet.cell(row=i, column=5).value = rest_response
                        xl_sheet.cell(row=i, column=6).value = str(allocation_summary)
                        print(rest_response)
                else:
                    error = "One of the input value is not valid, Please double check the record -->> " + str(i)
                    xl_sheet.cell(row=i, column=5).value = error
                    print(error)
            else:
                 error="Error in user max work hour check ! . . " + str(max_alloc)
                 xl_sheet.cell(row=i, column=5).value = error
                 print(error)

    xl_workbook.save(path)

#######################################################################


